//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as student to.
        /// </summary>
        internal static string AddAsStudentTo {
            get {
                return ResourceManager.GetString("AddAsStudentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add plug-in.
        /// </summary>
        internal static string AddPlugin {
            get {
                return ResourceManager.GetString("AddPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role.
        /// </summary>
        internal static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        internal static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        internal static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment web page.
        /// </summary>
        internal static string AssignmentWebPage {
            get {
                return ResourceManager.GetString("AssignmentWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain lowercase and uppercase letter, numerical digits and must be longer than 8 characters..
        /// </summary>
        internal static string ChangePasswordIntro {
            get {
                return ResourceManager.GetString("ChangePasswordIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Domino password has been successfully changed..
        /// </summary>
        internal static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected items?.
        /// </summary>
        internal static string ConfirmDeleteEntities {
            get {
                return ResourceManager.GetString("ConfirmDeleteEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to revoke the selected roles?.
        /// </summary>
        internal static string ConfirmDeleteRole {
            get {
                return ResourceManager.GetString("ConfirmDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        internal static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course web page.
        /// </summary>
        internal static string CourseWebPage {
            get {
                return ResourceManager.GetString("CourseWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current directory.
        /// </summary>
        internal static string CurrentDirectory {
            get {
                return ResourceManager.GetString("CurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files.
        /// </summary>
        internal static string DeleteFiles {
            get {
                return ResourceManager.GetString("DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start with empty folder and upload files again.
        /// </summary>
        internal static string DeleteFilesDetails {
            get {
                return ResourceManager.GetString("DeleteFilesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete role.
        /// </summary>
        internal static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (do not add).
        /// </summary>
        internal static string DoNotAdd {
            get {
                return ResourceManager.GetString("DoNotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        internal static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate users.
        /// </summary>
        internal static string DuplicateUsers {
            get {
                return ResourceManager.GetString("DuplicateUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date (soft).
        /// </summary>
        internal static string EndDateSoft {
            get {
                return ResourceManager.GetString("EndDateSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the processing of the request. You can submit a detailed error report by filling in the following form..
        /// </summary>
        internal static string ErrorIntro {
            get {
                return ResourceManager.GetString("ErrorIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate submission.
        /// </summary>
        internal static string EvaluateSubmission {
            get {
                return ResourceManager.GetString("EvaluateSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        internal static string Evaluation {
            get {
                return ResourceManager.GetString("Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error type.
        /// </summary>
        internal static string ExceptionType {
            get {
                return ResourceManager.GetString("ExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate password.
        /// </summary>
        internal static string GeneratePassword {
            get {
                return ResourceManager.GetString("GeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade type.
        /// </summary>
        internal static string GradeType {
            get {
                return ResourceManager.GetString("GradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade weight.
        /// </summary>
        internal static string GradeWeight {
            get {
                return ResourceManager.GetString("GradeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (hidden from student).
        /// </summary>
        internal static string HiddenFromStudent {
            get {
                return ResourceManager.GetString("HiddenFromStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import users.
        /// </summary>
        internal static string ImportUsers {
            get {
                return ResourceManager.GetString("ImportUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files.
        /// </summary>
        internal static string KeepFiles {
            get {
                return ResourceManager.GetString("KeepFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please verify your files before submission.
        /// </summary>
        internal static string KeepFilesDetails {
            get {
                return ResourceManager.GetString("KeepFilesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as read.
        /// </summary>
        internal static string MarkRead {
            get {
                return ResourceManager.GetString("MarkRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify assignment.
        /// </summary>
        internal static string ModifyAssignment {
            get {
                return ResourceManager.GetString("ModifyAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify course.
        /// </summary>
        internal static string ModifyCourse {
            get {
                return ResourceManager.GetString("ModifyCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify semester.
        /// </summary>
        internal static string ModifySemester {
            get {
                return ResourceManager.GetString("ModifySemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user.
        /// </summary>
        internal static string ModifyUser {
            get {
                return ResourceManager.GetString("ModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New assignment.
        /// </summary>
        internal static string NewAssignment {
            get {
                return ResourceManager.GetString("NewAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a new assignment.
        /// </summary>
        internal static string NewAssignmentDetails {
            get {
                return ResourceManager.GetString("NewAssignmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New course.
        /// </summary>
        internal static string NewCourse {
            get {
                return ResourceManager.GetString("NewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New semester.
        /// </summary>
        internal static string NewSemester {
            get {
                return ResourceManager.GetString("NewSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New submission.
        /// </summary>
        internal static string NewSubmission {
            get {
                return ResourceManager.GetString("NewSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload files and submit homework.
        /// </summary>
        internal static string NewSubmissionDetails {
            get {
                return ResourceManager.GetString("NewSubmissionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to start a new submission but files from an earlier
        ///submission are available. Do you want to keep these or start from
        ///an empty folder?.
        /// </summary>
        internal static string NewSubmissionIntro {
            get {
                return ResourceManager.GetString("NewSubmissionIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New users.
        /// </summary>
        internal static string NewUsers {
            get {
                return ResourceManager.GetString("NewUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assignments found..
        /// </summary>
        internal static string NoAssignments {
            get {
                return ResourceManager.GetString("NoAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No courses match the query..
        /// </summary>
        internal static string NoCourses {
            get {
                return ResourceManager.GetString("NoCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files have been uploaded so far..
        /// </summary>
        internal static string NoFiles {
            get {
                return ResourceManager.GetString("NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no grade assigned).
        /// </summary>
        internal static string NoGrade {
            get {
                return ResourceManager.GetString("NoGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has no roles yet..
        /// </summary>
        internal static string NoRoles {
            get {
                return ResourceManager.GetString("NoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No semesters match the query..
        /// </summary>
        internal static string NoSemesters {
            get {
                return ResourceManager.GetString("NoSemesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No submissions match the query..
        /// </summary>
        internal static string NoSubmissions {
            get {
                return ResourceManager.GetString("NoSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users match the query..
        /// </summary>
        internal static string NoUsers {
            get {
                return ResourceManager.GetString("NoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have forgotten you password, request a password reset..
        /// </summary>
        internal static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-in.
        /// </summary>
        internal static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-ins.
        /// </summary>
        internal static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read only.
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me on this computer.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replied.
        /// </summary>
        internal static string ReplyDate {
            get {
                return ResourceManager.GetString("ReplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reset your password, please enter your e-mail address..
        /// </summary>
        internal static string ResetPasswordIntro {
            get {
                return ResourceManager.GetString("ResetPasswordIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail with a password reset link has been sent to your e-mail address..
        /// </summary>
        internal static string ResetPasswordResults {
            get {
                return ResourceManager.GetString("ResetPasswordResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save grade.
        /// </summary>
        internal static string SaveGrade {
            get {
                return ResourceManager.GetString("SaveGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (select course).
        /// </summary>
        internal static string SelectCourse {
            get {
                return ResourceManager.GetString("SelectCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (select grade type).
        /// </summary>
        internal static string SelectGradeType {
            get {
                return ResourceManager.GetString("SelectGradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (select plug-in).
        /// </summary>
        internal static string SelectPlugin {
            get {
                return ResourceManager.GetString("SelectPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (select role).
        /// </summary>
        internal static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (select semester).
        /// </summary>
        internal static string SelectSemester {
            get {
                return ResourceManager.GetString("SelectSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        internal static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semesters.
        /// </summary>
        internal static string Semesters {
            get {
                return ResourceManager.GetString("Semesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send reply.
        /// </summary>
        internal static string SendReply {
            get {
                return ResourceManager.GetString("SendReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you need to be a registered user to use Domino.
        /// </summary>
        internal static string SignInFormDetails {
            get {
                return ResourceManager.GetString("SignInFormDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to Domino.
        /// </summary>
        internal static string SignInFormLabel {
            get {
                return ResourceManager.GetString("SignInFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start using Domino, please sign in with your existing credentials..
        /// </summary>
        internal static string SignInIntro {
            get {
                return ResourceManager.GetString("SignInIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully signed out from Domino..
        /// </summary>
        internal static string SignOutSuccess {
            get {
                return ResourceManager.GetString("SignOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student&apos;s comments.
        /// </summary>
        internal static string StudentComments {
            get {
                return ResourceManager.GetString("StudentComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission.
        /// </summary>
        internal static string Submission {
            get {
                return ResourceManager.GetString("Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        internal static string SubmissionDate {
            get {
                return ResourceManager.GetString("SubmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissions.
        /// </summary>
        internal static string Submissions {
            get {
                return ResourceManager.GetString("Submissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your uploaded files have been successfully submitted..
        /// </summary>
        internal static string SubmissionSuccess {
            get {
                return ResourceManager.GetString("SubmissionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your user account.
        /// </summary>
        internal static string UpdateUserAccount {
            get {
                return ResourceManager.GetString("UpdateUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user account has been successfully updated..
        /// </summary>
        internal static string UpdateUserAccountSuccess {
            get {
                return ResourceManager.GetString("UpdateUserAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded files.
        /// </summary>
        internal static string UploadedFiles {
            get {
                return ResourceManager.GetString("UploadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list file.
        /// </summary>
        internal static string UserListFile {
            get {
                return ResourceManager.GetString("UserListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles.
        /// </summary>
        internal static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your assignments.
        /// </summary>
        internal static string ViewAssignments {
            get {
                return ResourceManager.GetString("ViewAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see all your assignments and submission.
        /// </summary>
        internal static string ViewAssignmentsDetails {
            get {
                return ResourceManager.GetString("ViewAssignmentsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your courses.
        /// </summary>
        internal static string ViewCourses {
            get {
                return ResourceManager.GetString("ViewCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see all courses you are registered to.
        /// </summary>
        internal static string ViewCoursesDetails {
            get {
                return ResourceManager.GetString("ViewCoursesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (visible to student).
        /// </summary>
        internal static string VisibleToStudent {
            get {
                return ResourceManager.GetString("VisibleToStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web page.
        /// </summary>
        internal static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Domino!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
